name: Huffman Compressor

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # Triggers for version tags like v1.0
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: Linux
          - os: windows-latest
            artifact_name: Windows
          - os: macos-latest
            artifact_name: macOS

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Binary
        run: cmake --build build --config Release --parallel

      - name: Package (Install)
        # This creates the 'dist' folder with /bin, install scripts, and README
        run: cmake --install build --config Release --prefix dist

      - name: Rename Output Folder
        shell: bash
        run: mv dist Huffman-${{ matrix.artifact_name }}

      - name: Test Installation (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cd Huffman-${{ matrix.artifact_name }}
          echo [STEP 1] Running Root Installer...
          call .\install.bat
          
          echo [STEP 2] Mapping Toolchain to GitHub Path...
          echo %USERPROFILE%\.huff_toolchain\bin>> %GITHUB_PATH%

      - name: Verify Logic (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Enough thinking." > test.txt
          huff -e test.txt
          if exist "test.txt.hdta" ( echo [OK] Encoded ) else ( exit 1 )
          huff -d test.txt.hdta test.txt.htbl
          if exist "test(decoded).txt" ( echo [OK] Decoded ) else ( exit 1 )

      - name: Test Installation (Unix)
        if: runner.os != 'Windows'
        run: |
          cd Huffman-${{ matrix.artifact_name }}
          echo "[STEP 1] Running Root Installer..."
          ./install.sh
          echo "$HOME/.huff_toolchain/bin" >> $GITHUB_PATH

      - name: Verify Logic (Unix)
        if: runner.os != 'Windows'
        run: |
          echo "Enough thinking." > test.txt
          huff -e test.txt
          huff -d test.txt.hdta test.txt.htbl
          if [ -f "test(decoded).txt" ]; then
              echo "✅ Round-trip Successful."
          else
              echo "❌ Round-trip Failed."
              exit 1
          fi

      - name: Create Zip File
        run: cmake -E tar cfv Huffman-${{ matrix.artifact_name }}.zip --format=zip Huffman-${{ matrix.artifact_name }}/

      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Huffman-${{ matrix.artifact_name }}.zip